### ISSUE TITLE
Error on variable assignment  in struct ResNet

### ISSUE THREAD

**Issue by dashuai009** [leimao/LibTorch-ResNet-CIFAR#1]
https://github.com/leimao/LibTorch-ResNet-CIFAR/blob/78d1cd6ee617df0b7412a89681891b5a69410a55/src/resnet.cpp#L176-L199

I think line 197 should be `m_groups = groups`.

**Comment by leimao** [comment]
Good catch. Do you mind creating a PR?

**Comment by leimao** [comment]
Approved #2. Thanks.
