### ISSUE TITLE
libtorch上可不可以加上预训练的权重去训练

### ISSUE THREAD

**Issue by hengyui** [leimao/LibTorch-ResNet-CIFAR#3]
libtorch上可不可以加上预训练的权重去训练

**Comment by leimao** [comment]
If I remember it correctly, the serialized model formats between PyTorch and LibTorch are different at the time when I tried it. There was no official API that allows you to load the pretrained weights from Torch Hub.
However, things might have been changed and you would better to figure this out on your own.
